import pandas as pd
import numpy as np
from pypfopt import expected_returns, risk_models
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices
from data.fetcher import get_historical_prices

def get_portfolio_prices(tickers, period="5y"):
    """
    Fetch historical prices for a list of tickers and return a clean DataFrame 
    where each column is a ticker's closing prices.
    """
    pricing_data = {}
    for t in tickers:
        hist = get_historical_prices(t, period=period)
        if hist is not None and not hist.empty and "Close" in hist.columns:
            pricing_data[t] = hist["Close"]
    
    # Combine and forward fill missing data
    if pricing_data:
        df = pd.DataFrame(pricing_data)
        df = df.ffill().dropna()
        return df
    return pd.DataFrame()

def generate_rebalance_plan(tickers, constraint_overrides=None, sector_constraints=None, sector_mapper=None, objective="max_sharpe"):
    """
    Generates an optimized portfolio weight allocation using PyPortfolioOpt.
    
    Args:
        tickers (list): List of ticker symbols.
        constraint_overrides (dict): Ticker -> (min_weight, max_weight) bounds generated by AI.
        sector_constraints (dict): Sector -> (min_weight, max_weight) bounds generated by AI.
        sector_mapper (dict): Ticker -> Sector string mapping.
        objective (str): "max_sharpe", "min_volatility".
        
    Returns:
        dict: containing "weights" and performance metrics.
    """
    df = get_portfolio_prices(tickers)
    
    if df.empty or len(df.columns) < 2:
        # Cannot optimize less than 2 valid assets, return equal weight
        return {"weights": {t: 1.0/len(tickers) for t in tickers}, "error": "Insufficient price data to compute correlation matrix."}
        
    # Only keep tickers we successfully fetched data for
    valid_tickers = list(df.columns)
    
    try:
        # Calculate Expected Returns and Sample Covariance
        mu = expected_returns.mean_historical_return(df)
        S = risk_models.sample_cov(df)
        
        # Need to use bounds instead of exact constraints otherwise numerical issues often happen
        # Default bounds: 0.0 (no shorting) to 0.4 (max 40% in one stock to enforce diversification)
        default_lb, default_ub = 0.0, 0.40
        bounds = []
        for t in valid_tickers:
            if constraint_overrides and t in constraint_overrides:
                lb, ub = constraint_overrides[t]
                # Safely parse bounds
                lb = max(0.0, min(float(lb), 1.0))
                ub = max(lb, min(float(ub), 1.0))
                bounds.append((lb, ub))
            else:
                bounds.append((default_lb, default_ub))
                
        # Handle case where the upper bounds sum to less than 1.0
        ub_sum = sum(b[1] for b in bounds)
        if ub_sum < 1.0:
            bounds = [(b[0], 1.0) for b in bounds] # Relax upper bounds to ensure we can invest 100%

        # Initialize Efficient Frontier
        ef = EfficientFrontier(mu, S, weight_bounds=bounds)
        
        # Apply Sector Constraints if provided
        applied_sector_bounds = {}
        if sector_constraints and sector_mapper:
            sector_lower = {}
            sector_upper = {}
            for sector, s_bounds in sector_constraints.items():
                # Safety checks
                sl = max(0.0, min(float(s_bounds[0]), 1.0))
                su = max(sl, min(float(s_bounds[1]), 1.0))
                sector_lower[sector] = sl
                sector_upper[sector] = su
                applied_sector_bounds[sector] = (sl, su)
            
            try:
                ef.add_sector_constraints(sector_mapper, sector_lower, sector_upper)
            except Exception as e:
                print(f"Warning: Could not apply sector constraints: {e}")

        if objective == "max_sharpe":
            raw_weights = ef.max_sharpe()
        elif objective == "min_volatility":
            raw_weights = ef.min_volatility()
        else:
            raw_weights = ef.max_sharpe() # default
            
        cleaned_weights = ef.clean_weights()
        
        # Ensure all original requested tickers are in the return dict, even if 0
        final_weights = {t: cleaned_weights.get(t, 0.0) for t in tickers}
        
        # Performance stats: (expected_annual_return, annual_volatility, sharpe_ratio)
        ret, vol, sharpe = ef.portfolio_performance()
        
        return {
            "weights": final_weights,
            "expected_annual_return": ret,
            "annual_volatility": vol,
            "sharpe_ratio": sharpe,
            "correlation_matrix": df.corr().values.tolist(),
            "correlation_tickers": valid_tickers,
            "applied_bounds": bounds,
            "applied_sector_bounds": applied_sector_bounds,
            "error": None
        }
    except Exception as e:
        # Optimization failed (infeasible constraints probably)
        return {
            "weights": {t: 1.0/len(tickers) for t in tickers},
            "error": f"Optimization failed: {str(e)}. Returning Equal Weight placeholder."
        }
